{% set version = '0.6.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rbokeh
  version: {{ version|replace("-", "_") }}

source:


  # You can add a hash for the file here, like md5, sha1 or sha256
  git_url: https://github.com/bokeh/rbokeh
  git_tag: v0.6.3
  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, lintr, roxygen2 (>= 5.0.0)
requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}git

  host:
    - r-base
    - r-r6
    - r-curl
    - r-digest
    - r-glue
    - r-hexbin
    - r-htmlwidgets
    - r-jsonlite
    - r-lattice
    - r-magrittr
    - r-maps
    - r-rlang
    - r-scales

  run:
    - r-base
    - r-r6
    - r-curl
    - r-digest
    - r-glue
    - r-hexbin
    - r-htmlwidgets
    - r-jsonlite
    - r-lattice
    - r-magrittr
    - r-maps
    - r-rlang
    - r-scales

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rbokeh')"           # [not win]
    - "\"%R%\" -e \"library('rbokeh')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://hafen.github.io/rbokeh https://github.com/bokeh/rbokeh
  license: MIT + file LICENSE
  summary: A native R plotting library that provides a flexible declarative interface for creating
    interactive web-based graphics, backed by the Bokeh visualization library <http://bokeh.pydata.org/>.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: rbokeh
# Title: R Interface for Bokeh
# Version: 0.6.3
# Authors@R: c( person("Ryan", "Hafen", email = "rhafen@gmail.com", role = c("aut", "cre")), person("Kenton", "Russell", email = "kent.russell@timelyportfolio.com", role = "ctb"), person("Jonathan", "Owen", email = "jonathanro@gmail.com", role = "ctb"), person("Barret", "Schloerke", email = "schloerke@gmail.com", role = "ctb"), person("Saptasrhi", "Guha", email = "saptarshi.guha@gmail.com", role = "ctb"), person("Continuum Analytics, Inc.", role = c("aut", "cph"), comment = "Bokeh library in htmlwidgets/lib, http://bokeh.pydata.org" ))
# Description: A native R plotting library that provides a flexible declarative interface for creating interactive web-based graphics, backed by the Bokeh visualization library <http://bokeh.pydata.org/>.
# URL: https://hafen.github.io/rbokeh https://github.com/bokeh/rbokeh
# BugReports: https://github.com/bokeh/rbokeh/issues
# License: MIT + file LICENSE
# LazyData: true
# NeedsCompilation: no
# Imports: R6, jsonlite, digest, methods, htmlwidgets, magrittr, curl, glue, rlang, scales, hexbin, lattice, maps
# Suggests: testthat, lintr, roxygen2 (>= 5.0.0)
# RoxygenNote: 6.0.1

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
