travis:
  secure:
    BINSTAR_TOKEN: fW6Y/fJh+geGJtfmB7UE/n4+9QLtO7gXuSPfg+pcfHPlxXBT0HCj0uFveoU/kT0daD3F8G59ZCAeMym+XDZvLJE5RaDVvEBr8yJRnKt0zMKo7YBdamcdvGCI5brGe8Yhu7a7muOxnpsgYiWqiCxvlbLLZrXphkU+VLJucAJFQUIDJwaMSam/9nDOckva3pPiI1ZPEeY6k8pGfQGd45r4n7ZEI/JXyBvWPFeAQJrrznYDlUzcdhCnHXbTobBf07ur3UkQ1N0wqbUxq9RukFgTMYt+M9tXP1SagxIN1qyPRMOQVASX37NHKphS7hZYQNMH4en2ZfYJg6/HhgKv7ImzgWfz+qmfm/CSFBu51zT0j+utWdO1dwbTrW17ZUEmqlBD4JDwVNAPbatrf/8xYw9+e2HdyHSLGWRT1RjDfbtLM5Sb5eSBP1eC+7kHjVseHhde19/8Hl54Xcbnb2ZrPEK7HguB2wR1VmgVflTiuKuHgA6Tw2gjUskzok2gI1+NI1TE7oBfZswp8ot4D9v/upP1NqYJz0cNnYu3bSwBepedHsh6NNItih7jc13gSNVZt8w9JeJ3AgADMqLwEWnpnrbuYUCNOajIcP8+jNBPa9jMSNdAc1wWWOihKpic2keroalHB+HQf0IJ0SSsoJbpZad2p4Qh+zR0T4jZBp6yWXHcK5k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
