travis:
  secure:
    BINSTAR_TOKEN: oWEruaZcgmVo35LzHDV19kOitwGuuTK+8oMOqD/kbiGdkQLcejwrG1KtCaz6o8R62G5wssXltUTBQ0Br2B7m/Alzb7rvhLaFzw/6OVkA/NQOac4qImVQgQqXCi+8RXA99ixckmBl7S3JJ4+OIRhwgyeSnSjcToUqqbTAMlq1BRFpO0UFjEhcNowT3VgN2CjG7WcttmJ/IX/9rErlWuQzLUDf7SAeUD7RZyEdVOTu111DpTbbfgSfqdxQJLAJyz9U0UHXaqX1Ddi6UXlAbJBgw8ZpMPzdom8ulrEoL3wRa4dOxuzkDF22Xex5CyqVIlOc7ovuldT9ZpDlOPgJ2zXaQYEXrZVfUXNmCWf/oCJaxhxUqBGGUMCEV+Gi+d5grNX/lSa/wxytuW9jQxAx0gdMM6+6jED4dpQq+hJKn2zrCrqZ0AWl7vrISZ+l1V2cmAlTcYfq0QpkCSvO6q0ahLnq0VGMbRbB2cV0AL0lfhJnqCfj7KCe+xaeuOKv8pD9Q2UhMq45p6bLvMt3BYPuF9+CdQdXv/yGvw1bnDfVzBw9ruv6SyHYGlf02QE6E6UTNaHkFrnZsuynPNyH54USc3qa0ZDYUp7YIIutg/OXOastukS+h10teUEi4Z1rzxSm5Ceei3Ctz1OzHjdlYQGWhbRP32EeEWXj6GW6il4cNVtEwAc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
