travis:
  secure:
    BINSTAR_TOKEN: x6b/lC+4zZdwomdNN2h1R3t2UkGSCGnDFhLKkujMa0IJ2yLOUjtvpixMfYSLuYoeGngW8xwFeWgI5IVTuFNRv+EhswAiRMIFXJpXJ6vIp4o4gb37RvYUIMXZ6SZzLs64P+qG0cPYMxftS72Z5qbR25LYOGy0SS0C8dotF/AlwBtABOsk3SFiC1kofq5rjbk91IK7o5h8I9DRPpX2IkXZDTrxipIgkYWlXyPSBxLxLp9NroIwv8Vv07L7rg+L1mrmkJeG1lJ233gVIQWnzzx0beaHEUOeNEerBMSfrBWw95aiYJTi+a9E9agACt067q714orU0Pt9bkUVSccq4XUgS7W9HK959832mA+JwrmVzYlyA0a2D573qM5U6KN9EeWwNlMUyrlbll4nfmWvAT0sveJAj+pxGSDwE/IANy8mnqCKyNEYV36sDpwlTkQfI8xqRuZscW9J6ccg4Emz+JvsZhqkeg1E5tgkN6CANVvPzLpti7iEOONmUHvMBlKW+uKjeZboLnLn4zpl66Fek8Goy//Hd/KEiuQUNnoot7W2agKGtlYzLBCftASW9U8Lbi0Brt4t3ds2xS2p2N+42CfgSQVnfOgzZ5qQSS4EJNw9dh0z3CG/mj7OkXvp6s599UY7jqHttSQEpjemzaBe+4k/oB467Z8Tn0aOCSdJWCQD9Ds=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
