travis:
  secure:
    BINSTAR_TOKEN: DzT6oEZieWbJTMXfwFIE68z7ecydrJW2yNSMthRJQKy0DpluKeUOOIceCY8pQDWJTa4d8ihDG5G4z3pJHjsSj9kcSpvfgKcryhIEE9wD5IxcSYeFuqi7y+D7UT9cPxVomJ1Xa2y+7DY2BpbeqL+eaJADszKFW8m2pfRCEerrvdQogbRkQZqPXb+o7pFj3aDhebkRz8/1jQqFgXEuojBoEW5R+POBNpDfNBqOIfPJHcg39dO5giAu75soDx95IB/9SZyzt+fFtUVMJl6FIDSORuVVsv6jLbupUbmP/RfgqmgNdkilQgJ0OKTgo1TB7t1z6vUa+xoVFA7Tr6w9amQMb5sS6Zl+aDUtbDoq7RNZM14+guktKn9UkZji5emgvIS6ZaT032M+Ack0byl7Pplus3AT/WYdwmMLlVNWtBLB67J5rOlh4xCoOLiccAOuHqxVyg9MRsZGR7lnyX/fTtpq/hzhEAeAlRBZ7G3eLPCXcRyrSy/5OPtCOOVA7HaGN4EBrDo+FrbTWU/ZO0fTQwBFITfjBFd0t1/5IRuczCtHGUgWwLOd3F8lkEINE0xXsa6D37rOiDHdcCA3bjnXjPdOwh0uQBPAyUM7WEriFeL9QEpl7J1mBo9eEYMSjviV2660V/odI9zXURgyWju+PheLRXkUASmmwjgSIkLKRQuJ1r0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
